#!/usr/bin/env python3
"""Build deterministic OpenDevIndex search/catalog artifacts."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

from catalog_utils import category_counts, collect_entries, discover_catalogs

TOKEN_RE = re.compile(r"[^a-z0-9.+_-]+")


def normalize_text(value: object) -> str:
    text = str(value or "").casefold()
    return " ".join(part for part in TOKEN_RE.split(text) if part)


def search_text(entry: dict) -> str:
    values: list[str] = [
        entry["module_ref"],
        entry["id"],
        entry["name"],
        entry["category"],
        entry["summary"],
        *entry.get("tags", []),
        *entry.get("use_cases", []),
        *entry.get("key_points", []),
    ]
    return normalize_text(" ".join(values))


def public_record(entry: dict) -> dict:
    return {
        "ref": entry["module_ref"],
        "slug": entry["id"],
        "name": entry["name"],
        "category": entry["category"],
        "summary": entry["summary"],
        "tags": entry.get("tags", []),
        "use_cases": entry.get("use_cases", []),
        "key_points": entry.get("key_points", []),
        "homepage": entry.get("homepage"),
        "repository": entry.get("repository"),
        "sources": entry.get("sources", []),
        "verified_at": entry["verified_at"],
        "milestone": entry["milestone"],
    }


def search_record(entry: dict) -> dict:
    return {
        "ref": entry["module_ref"],
        "slug": entry["id"],
        "name": entry["name"],
        "category": entry["category"],
        "summary": entry["summary"],
        "tags": entry.get("tags", []),
        "use_cases": entry.get("use_cases", []),
        "key_points": entry.get("key_points", []),
        "homepage": entry.get("homepage"),
        "repository": entry.get("repository"),
        "verified_at": entry["verified_at"],
        "search_text": search_text(entry),
    }


def render_markdown(entries: list[dict], counts: dict[str, int]) -> str:
    lines = [
        "# OpenDevIndex Catalog",
        "",
        "Generated from validated curated catalogs. Do not edit this file by hand.",
        "",
        f"**Modules:** {len(entries)}",
        "",
        "## Categories",
        "",
        "| Category | Modules |",
        "| --- | ---: |",
    ]
    for category, count in counts.items():
        lines.append(f"| `{category}` | {count} |")

    current: str | None = None
    for entry in entries:
        if entry["category"] != current:
            current = entry["category"]
            lines.extend(["", f"## {current}", "", "| Module | Summary | Tags |", "| --- | --- | --- |"])
        tags = ", ".join(f"`{tag}`" for tag in entry.get("tags", []))
        summary = entry["summary"].replace("|", "\\|")
        name = entry["name"].replace("|", "\\|")
        lines.append(f"| **{name}** (`{entry['module_ref']}`) | {summary} | {tags} |")

    lines.append("")
    return "\n".join(lines)


def write_json(path: Path, payload: object) -> None:
    path.write_text(
        json.dumps(payload, indent=2, ensure_ascii=False, sort_keys=True) + "\n",
        encoding="utf-8",
    )


def build(catalog_dir: Path, output_dir: Path) -> dict:
    paths = discover_catalogs(catalog_dir)
    entries, catalogs = collect_entries(paths)
    counts = category_counts(entries)
    output_dir.mkdir(parents=True, exist_ok=True)

    catalog_payload = {
        "schema_version": 1,
        "module_count": len(entries),
        "category_counts": counts,
        "catalogs": catalogs,
        "entries": [public_record(entry) for entry in entries],
    }
    search_payload = {
        "schema_version": 1,
        "module_count": len(entries),
        "category_counts": counts,
        "entries": [search_record(entry) for entry in entries],
    }

    write_json(output_dir / "catalog.json", catalog_payload)
    write_json(output_dir / "search.json", search_payload)
    (output_dir / "catalog.md").write_text(render_markdown(entries, counts), encoding="utf-8")

    return {
        "module_count": len(entries),
        "category_counts": counts,
        "catalogs": [item["path"] for item in catalogs],
        "output_dir": output_dir.as_posix(),
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--catalog-dir", default="catalog")
    parser.add_argument("--output-dir", default="dist/index")
    args = parser.parse_args()

    result = build(Path(args.catalog_dir), Path(args.output_dir))
    print(
        "OpenDevIndex search index built: "
        f"{result['module_count']} modules -> {result['output_dir']}"
    )
    for category, count in result["category_counts"].items():
        print(f"- {category}: {count}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
